authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include('mainapp.urls', namespace='mainapp')),

    path('accounts/', include('authapp.urls', namespace='authapp')),

    path('admin/', admin.site.urls),
]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('about_us/', mainapp.about_us, name='about_us'),
]

authapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(verbose_name='Город', max_length=64, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = ""
        self.fields['password'].label = ""
        self.fields['username'].widget.attrs['placeholder'] = f'Логин'
        self.fields['password'].widget.attrs['placeholder'] = f'Пароль'

        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'input-line full-width'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = ""
        self.fields['password1'].label = ""
        self.fields['password2'].label = ""
        self.fields['username'].widget.attrs['placeholder'] = f'Логин'
        self.fields['password1'].widget.attrs['placeholder'] = f'Пароль'
        self.fields['password2'].widget.attrs['placeholder'] = f'Повтор пароля '
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'input-line full-width'
            item.help_text = ''

authapp/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('mainapp:index'))
    else:
        form = LoginForm()

    context = {
        'form': form,
        'page_title': 'авторизация',
    }
    return render(request, 'authapp/login.html', context)


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        form = RegisterForm()
    context = {
        'page_title': 'регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)

@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('mainapp:index'))

mainapp/views.py
from django.shortcuts import render

from mainapp.models import City
import random


def index(request):
    city = City.objects.all()

    context = {
        'title': 'Главная',
        'random': random.choice(city),
    }
    return render(request, 'mainapp/index.html', context)


def about_us(request):
    context = {
        'title': 'О нас',
    }
    return render(request, 'mainapp/about_us.html', context)

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}


{% block content %}

<div class='bold-line'></div>
<div class='container'>
  <div class='window'>
    <div class='overlay'></div>
    <div class='content'>
      <div class='welcome'>Вход</div>
      <form class="input-fields" method="post">
        {% csrf_token %}
        {{ form.as_p }}
          <div class='spacing'>Не зарегистрированы ? <span class='highlight'><a href="{% url 'authapp:register' %}">Зарегистрироваться</a></span></div>
        <div><button class='ghost-round full-width'>Войти</button></div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}

{% block content %}

<div class='bold-line'></div>
<div class='container'>
  <div class='window'>
    <div class='overlay'></div>
    <div class='content'>
      <div class='welcome'>Регистрация</div>
      <form class="input-fields" method="post">
        {% csrf_token %}
        {{ form.as_p }}
          <div class='spacing'>Уже зарегистрированы ? <span class='highlight'><a href="{% url 'authapp:login' %}">Войти</a></span></div>
        <div><button class='ghost-round full-width'>Войти</button></div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

mainapp/templates/mainapp/about_us.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>О нас</h1>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>{{ page_title|default:"главная"|capfirst }}</title>
        {% block css %}
            <link rel="stylesheet" href="{% static 'css/main.css' %}">
        {% endblock %}
    </head>
    <body>
        <nav class="navMenu">
            <ul>
                <li><a href="{% url 'mainapp:index' %}">Главная</a></li>
                <li><a href="{% url 'mainapp:about_us' %}">О нас</a></li>


                {% if user.is_authenticated %}
                        <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'authapp:login' %}">Войти</a></li>
                        <li><a href="{% url 'authapp:register' %}">Зарегистрироваться</a></li>
                    {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Главная</h1>

    <p class="city">
    {{ random }}
    </p>
{% endblock %}